"""Custom tool for preparing patch proposal artifacts.

The full implementation will later convert model output into a stable,
serializable patch artifact that can be reviewed by the validation agent.
"""

import json
from pathlib import Path

from agents.patch_agent.schema import PatchArtifact, PatchProposal


def _model_to_json_dict(proposal: PatchProposal) -> dict[str, object]:
    """Convert a Pydantic model to a JSON-safe dictionary.

    This helper supports both Pydantic v1 and v2 style serialization.
    """

    if hasattr(proposal, "model_dump"):
        return proposal.model_dump(mode="json")
    return proposal.dict()


def build_patch_output_path(issue_id: str, output_dir: str = "outputs/patches") -> Path:
    """Create a deterministic output path for a proposed patch artifact.

    Args:
        issue_id: Unique issue identifier used in the output filename.
        output_dir: Directory where patch proposal files will be stored.

    Returns:
        Path pointing to the target patch artifact location.

    Raises:
        ValueError: If the issue identifier is empty or only whitespace.
    """

    normalized_issue_id = issue_id.strip()
    if not normalized_issue_id:
        raise ValueError("issue_id must be a non-empty string")

    return Path(output_dir) / f"{normalized_issue_id}_patch.json"


def write_patch_artifact(
    proposal: PatchProposal,
    output_dir: str = "outputs/patches",
) -> PatchArtifact:
    """Serialize a patch proposal into a JSON artifact on disk.

    Args:
        proposal: Structured proposal generated by the Patch Generation Agent.
        output_dir: Directory where serialized patch artifacts are stored.

    Returns:
        PatchArtifact containing the proposal and written file path.

    Raises:
        OSError: If the output directory or file cannot be created.
        TypeError: If the proposal cannot be serialized into JSON.
    """

    output_path = build_patch_output_path(proposal.issue_id, output_dir=output_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    artifact_payload = _model_to_json_dict(proposal)
    with output_path.open("w", encoding="utf-8") as file_handle:
        json.dump(artifact_payload, file_handle, indent=2)

    return PatchArtifact(proposal=proposal, artifact_path=str(output_path))
