"""Custom tool for preparing patch proposal artifacts.

This tool turns a structured patch proposal into stable disk artifacts
that can be inspected by downstream agents or during demonstrations.
"""

import json
from pathlib import Path

from agents.patch_agent.schema import PatchArtifact, PatchChangePlan, PatchProposal


def _model_to_json_dict(proposal: PatchProposal) -> dict[str, object]:
    """Convert a Pydantic model to a JSON-safe dictionary.

    This helper supports both Pydantic v1 and v2 style serialization.
    """

    if hasattr(proposal, "model_dump"):
        return proposal.model_dump(mode="json")
    return proposal.dict()


def build_patch_output_path(issue_id: str, output_dir: str = "outputs/patches") -> Path:
    """Create a deterministic output path for a proposed patch artifact.

    Args:
        issue_id: Unique issue identifier used in the output filename.
        output_dir: Directory where patch proposal files will be stored.

    Returns:
        Path pointing to the target patch artifact location.

    Raises:
        ValueError: If the issue identifier is empty or only whitespace.
    """

    normalized_issue_id = issue_id.strip()
    if not normalized_issue_id:
        raise ValueError("issue_id must be a non-empty string")

    return Path(output_dir) / f"{normalized_issue_id}_patch.json"


def build_patch_draft_path(issue_id: str, output_dir: str = "outputs/patches") -> Path:
    """Create a deterministic path for the unified-diff patch draft.

    Args:
        issue_id: Unique issue identifier used in the output filename.
        output_dir: Directory where patch draft files will be stored.

    Returns:
        Path pointing to the target draft patch location.
    """

    normalized_issue_id = issue_id.strip()
    if not normalized_issue_id:
        raise ValueError("issue_id must be a non-empty string")

    return Path(output_dir) / f"{normalized_issue_id}_patch.diff"


def _build_file_diff(change: PatchChangePlan) -> str:
    """Create a lightweight unified-diff section for one planned file.

    Args:
        change: File-level patch plan produced by the Patch Generation Agent.

    Returns:
        Multi-line diff text representing the planned change.
    """

    change_summary = change.change_summary.rstrip(".")
    evidence = change.evidence.rstrip(".")
    return "\n".join(
        [
            f"diff --git a/{change.file_path} b/{change.file_path}",
            f"--- a/{change.file_path}",
            f"+++ b/{change.file_path}",
            "@@",
            f"-# Existing logic related to: {evidence}",
            f"+# Patch intent: {change_summary}",
            "",
        ]
    )


def build_patch_draft(proposal: PatchProposal) -> str:
    """Render a patch proposal into a unified-diff-style draft string.

    Args:
        proposal: Structured patch proposal generated by the patch agent.

    Returns:
        Multi-file patch draft text suitable for artifact storage.

    Raises:
        ValueError: If the proposal does not contain any change-plan items.
    """

    if not proposal.change_plan:
        raise ValueError("proposal.change_plan must contain at least one planned change")

    header = [
        f"# Issue: {proposal.issue_id}",
        f"# Summary: {proposal.summary}",
        f"# Risk: {proposal.risk_level}",
        "",
    ]
    diff_sections = [_build_file_diff(change) for change in proposal.change_plan]
    return "\n".join(header + diff_sections).strip() + "\n"


def write_patch_artifact(
    proposal: PatchProposal,
    output_dir: str = "outputs/patches",
) -> PatchArtifact:
    """Serialize a patch proposal into a JSON artifact on disk.

    Args:
        proposal: Structured proposal generated by the Patch Generation Agent.
        output_dir: Directory where serialized patch artifacts are stored.

    Returns:
        PatchArtifact containing the proposal and written file path.

    Raises:
        OSError: If the output directory or file cannot be created.
        TypeError: If the proposal cannot be serialized into JSON.
    """

    output_path = build_patch_output_path(proposal.issue_id, output_dir=output_dir)
    draft_path = build_patch_draft_path(proposal.issue_id, output_dir=output_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    patch_draft = build_patch_draft(proposal)

    with draft_path.open("w", encoding="utf-8") as file_handle:
        file_handle.write(patch_draft)

    artifact_payload = _model_to_json_dict(proposal)
    with output_path.open("w", encoding="utf-8") as file_handle:
        json.dump(artifact_payload, file_handle, indent=2)

    return PatchArtifact(
        proposal=proposal,
        artifact_path=str(output_path),
        patch_draft=patch_draft,
        patch_draft_path=str(draft_path),
    )
